create table produto (
    id bigint generated by default as identity,
    nome varchar(255),
    descricao varchar(255),
    img_link varchar,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_ultima_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id)
);

CREATE TABLE contato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    email VARCHAR(255),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_ultima_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_ultima_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_usuario VARCHAR(9),
    PRIMARY KEY (id),
    UNIQUE (email, nome)
);

INSERT INTO usuario
(id, nome, email, senha, data_criacao, data_ultima_alteracao)
VALUES(1, 'admin', 'admin@ecommerce.com', '$2a$10$VM7Gg2.MCVBECX5xYWJG2OtTDemJ1TVYQBegTy1HBd8Zus678E9aC', CURRENT_TIMESTAMP, null);